ALTER TABLE USER_SYSTEM 
    ALTER COLUMN name SET NOT NULL,
    ALTER COLUMN username SET NOT NULL,
    ALTER COLUMN email SET NOT NULL,
    ALTER COLUMN password SET NOT NULL;
    ALTER COLUMN role SET NOT NULL;
    ALTER COLUMN dt_insert SET NOT NULL;