CREATE TABLE IF NOT EXISTS USER_SYSTEM(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    username UNIQUE VARCHAR(20) NOT NULL,
    email UNIQUE VARCHAR(20) NOT NULL,
    password VARCHAR (150) NOT NULL,
    role VARCHAR(10) NOT NULL,
    dt_insert TIMESTAMP NOT NULL
);