CREATE TABLE IF NOT EXISTS COURSE (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(150) NOT NULL,
    instructor_id INTEGER REFERENCES USER_SYSTEM (ID) NOT NULL,
    description VARCHAR(200),
    status VARCHAR (20) NOT NULL,
    dt_delete TIMESTAMP,
    dt_insert TIMESTAMP NOT NULL
);