CREATE TABLE IF NOT EXISTS NPS (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    student_id INTEGER REFERENCES USER_SYSTEM (ID) NOT NULL,
    course_id INTEGER REFERENCES COURSE (ID) NOT NULL,
    score INTEGER NOT NULL,
    ds_score VARCHAR(200),
    dt_registration TIMESTAMP NOT NULL
);